### ISSUE TITLE
h265 file open failed

### ISSUE THREAD

**Issue by sgf201** [lheric/GitlHEVCAnalyzer#30]
[yyyyy.txt](https://github.com/lheric/GitlHEVCAnalyzer/files/12449956/yyyyy.txt)
it is a h265 file but opened failed

**Comment by RealSting** [comment]
> [yyyyy.txt](https://github.com/lheric/GitlHEVCAnalyzer/files/12449956/yyyyy.txt) it is a h265 file but opened failed

not crash.
try again. (rename to yyyyy.hevc)
it works to my side :)
